# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f707899abcbf1208e9c2630c4678b2d9d72153cd7a3ffc4c5d664e381679b618ec0f9ada2a594dc405d9580a0ad1ecd2145524fa67a04f4bcb71db4248ab471a

test:
  secret_key_base: 754dcb380bd2939cbe8d5c4f9c35a1dfdc53e48e14975b5f2dc3d716c5140f531426cbb3c123d5151a11f1890e63425cfa8d9ad15bcd405d9338f5742584bdc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
